services:
  python-app:
    build: "./src"
    ports:
      - 8000:8000
    env_file:
      - ./src/.env
    depends_on:
      - sql
  sql:
    build: "./sql"
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./sql/.env